services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn lowpolypy.server:app --reload --host 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
