# fly.toml app configuration file generated for lowpolypy on 2025-01-26T01:42:01+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lowpolypy'
primary_region = 'iad'

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '4gb'
cpu_kind = 'shared'
cpus = 1
