[package]
name = "lowpolyrs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["cargo", "derive"] }
env_logger = "0.11.6"
image = "0.25.5"
imageproc = "0.25.0"
log = "0.4.25"
rand = "0.8.5"
